sonar.projectKey=amurlaniakea_citefid
sonar.organization=amurlaniakea
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
